In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('11-iris.csv')
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [3]:
df.info() # We have a 1 object 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [4]:
df.describe() # Values are normal

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


In [5]:
df.drop(columns = 'Id' , axis = 1 , inplace = True)
df.head() # We dont need this column

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [6]:
X = df.drop(columns = 'Species' , axis = 1)
y = df['Species']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.25 , random_state = 15 )

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
# ---------------------------------------------------- GaussianNB ------------------------------------------------------------------------------

In [11]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [12]:
gnb.fit(X_train_scaled , y_train)
y_pred = gnb.predict(X_test_scaled)

In [13]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report 

print('Accuracy Score : ' , accuracy_score(y_test , y_pred))
print('Classificaation Report : \n' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred))

Accuracy Score :  1.0
Classificaation Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

Confusion Matrix : 
 [[12  0  0]
 [ 0 14  0]
 [ 0  0 12]]


In [14]:
# ------------------------------------------- Logistic Regression --------------------------------------------------------------------------------

In [15]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [16]:
logistic.fit(X_train_scaled , y_train)

y_pred = logistic.predict(X_test_scaled)

print('Accuracy Score : ' , accuracy_score(y_test , y_pred))
print('Classificaation Report : \n' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred))

Accuracy Score :  1.0
Classificaation Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

Confusion Matrix : 
 [[12  0  0]
 [ 0 14  0]
 [ 0  0 12]]


In [17]:
# ----------------------------------------------- SVM --------------------------------------------------------------------------------------------

In [18]:
from sklearn.svm import SVC

In [19]:
svc = SVC()
svc.fit(X_train_scaled , y_train)
y_pred = svc.predict(X_test_scaled)

print('Accuracy Score : ' , accuracy_score(y_test , y_pred))
print('Classificaation Report : \n' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred))

Accuracy Score :  1.0
Classificaation Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

Confusion Matrix : 
 [[12  0  0]
 [ 0 14  0]
 [ 0  0 12]]
