In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('6-bank_customers.csv')
df.head()

,age,job_satisfaction,balance,duration_last_call,num_contacts_last_month,has_housing_loan,has_personal_loan,communication_type,days_since_last_contact,campaign_response_score,subscribed
0,-0.377957,1.043895,1.043494,-0.101838,-1.617442,0.402713,0.913601,-0.067192,0.175471,-1.049646,0
1,-0.325259,1.276263,-0.686123,-2.463205,-0.489426,-0.240715,-1.469496,1.006633,-0.833692,0.957744,0
2,0.739019,-0.600903,-0.177294,1.335714,-0.817332,-0.790047,1.457365,-0.218981,0.878643,-1.257740,0
3,0.474312,-1.103002,1.189936,-0.800186,0.912377,-0.406451,-1.130950,1.985111,1.379029,1.041768,1
4,0.927365,1.114796,0.080284,1.261064,0.761179,0.921563,0.440832,0.184645,-1.567739,-0.142107,1


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [4]:
df.describe()

,age,job_satisfaction,balance,duration_last_call,num_contacts_last_month,has_housing_loan,has_personal_loan,communication_type,days_since_last_contact,campaign_response_score,subscribed
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.015084,0.031559,0.045069,-0.020771,0.016769,-0.042135,-0.025139,0.058969,-0.015637,0.022327,0.503000
std,1.021848,1.004281,1.006910,1.392738,1.268761,1.029279,1.267490,0.992629,1.000664,1.135131,0.500241
min,-3.718638,-3.116027,-3.534257,-4.999018,-2.587178,-3.250031,-4.932878,-3.187779,-2.819987,-2.071129,0.000000
25%,-0.685005,-0.657545,-0.647051,-1.057938,-0.981320,-0.722970,-0.855392,-0.598669,-0.693330,-1.050201,0.000000
50%,-0.030546,0.045869,0.040586,0.204506,-0.317137,-0.022343,0.148199,0.052208,0.018807,-0.037530,1.000000
75%,0.662124,0.701601,0.731615,1.061181,1.017388,0.596557,1.020255,0.722446,0.641338,0.760782,1.000000
max,2.765266,2.658705,3.357941,3.477210,3.954873,3.206344,2.343380,3.600187,3.477044,4.124285,1.000000


In [5]:
# Datamız temiz data temziliğine gerek yok hatta değerler zaten scale edilmiş olduğu için scale de etmeyceğiz

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('subscribed' , axis = 1)
y = df['subscribed']

In [8]:
X_train , X_test , y_train , y_test = train_test_split(X , y , random_state = 15 , test_size = 0.3)

In [9]:
# Scale yapmıyoruz veriler zaten scale edilmiş halde

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
logistic = LogisticRegression()

In [12]:
logistic.fit(X_train , y_train)
y_pred = logistic.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix

In [38]:
print('Accuary Score : ' , accuracy_score(y_test , y_pred))
print('Classification Report :\n ' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred)) 

Accuary Score :  0.92
Classification Report :
                precision    recall  f1-score   support

           0       0.90      0.94      0.92       145
           1       0.94      0.90      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion Matrix : 
 [[136   9]
 [ 15 140]]


In [15]:
# Doğruluk oranı %92 
# Precision ve recall gayet yakın ve düzgün 
# F1 Score da yüksek 
# True Positive = 134  --- True Negative = 142 -->> Gayet başarılı tahminler ve istatistikler 

In [16]:
# Hyperparameter Tuning 

In [17]:
model = LogisticRegression()

In [18]:
penalty = ['l1' , 'l2' , 'elasticnet']
c_values = [100 , 10 , 0 , 0.1 , 0.01]
solver = ['lbfgs' , 'liblinear' , 'newton-cg' , 'newton-cholesky' , 'sag' , 'saga']

In [19]:
params  = dict(penalty = penalty , C = c_values , solver = solver)

In [20]:
from sklearn.model_selection import GridSearchCV , StratifiedKFold

In [21]:
cv = StratifiedKFold()

In [22]:
grid = GridSearchCV(estimator = model , param_grid = params , scoring = 'accuracy' , n_jobs=-1 , cv = 5 )

In [23]:
grid

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [24]:
grid.fit(X_train , y_train)

C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
290 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solv

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [25]:
grid.best_params_

{'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}

In [26]:
grid.best_score_

np.float64(0.9228571428571429)

In [27]:
y_pred = grid.predict(X_test)

In [28]:
print('Accuary Score : ' , accuracy_score(y_test , y_pred))
print('Classification Report : \n' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred)) 

Accuary Score :  0.9233333333333333
Classification Report : 
               precision    recall  f1-score   support

           0       0.90      0.94      0.92       145
           1       0.95      0.90      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion Matrix : 
 [[137   8]
 [ 15 140]]


In [29]:
# Datamız temiz olduğu için burada hipermarameter tuning çok fazla etki etmedi ama ilerde göreceğiz ki edecek

In [30]:
from  sklearn.model_selection import RandomizedSearchCV

In [31]:
model = LogisticRegression()

In [32]:
random = RandomizedSearchCV(estimator = model , param_distributions = params , n_iter = 10 , scoring = 'accuracy' , n_jobs = -1 , cv = 5 )

In [33]:
random.fit(X_train , y_train)

C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\MSI-NB\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [34]:
random.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}

In [35]:
random.best_score_

np.float64(0.9214285714285715)

In [36]:
y_pred = random.predict(X_test)

In [37]:
print('Accuary Score : ' , accuracy_score(y_test , y_pred))
print('Classification Report : ' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred)) 

Accuary Score :  0.92
Classification Report :                precision    recall  f1-score   support

           0       0.90      0.94      0.92       145
           1       0.94      0.90      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion Matrix : 
 [[136   9]
 [ 15 140]]
